// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleCentral.Data;

#nullable disable

namespace ScheduleCentral.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231155655_AddSelfRegistrationFields")]
    partial class AddSelfRegistrationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "34f669a9-3c3b-4c0d-a320-c1143f295621",
                            ConcurrencyStamp = "8c282101-499c-47c5-acef-3ca7eec41970",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "5798b3f2-1d5d-4f81-a75d-6c1b3f9d44e5",
                            ConcurrencyStamp = "e8fad9f0-acd8-420b-a688-773f5c97e8f5",
                            Name = "ProgramOfficer",
                            NormalizedName = "PROGRAMOFFICER"
                        },
                        new
                        {
                            Id = "98c2d1b8-2a2b-4d4b-9e0a-7c9d1a8f6d53",
                            ConcurrencyStamp = "600546b9-99ce-4cfa-9364-e0cf5329982f",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "62a4c8e7-6b4e-4f3a-a5c1-8b0d2e4f7c9e",
                            ConcurrencyStamp = "74e5ec52-900e-4028-8aaa-9c27ada4e878",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "2a8e9d3c-5f7a-4b6d-9c1e-0d2f3a4e5b6c",
                            ConcurrencyStamp = "119ff3f0-de3f-4adc-8400-eb7ff4e118f7",
                            Name = "Department",
                            NormalizedName = "DEPARTMENT"
                        },
                        new
                        {
                            Id = "d1b5f2c4-8g9h-4i0j-k2l3-m4n5o6p7q8r9",
                            ConcurrencyStamp = "7063d109-0e78-4d3c-ad0d-709cf909a3f0",
                            Name = "TopManagement",
                            NormalizedName = "TOPMANAGEMENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b1f8e5d0-8b1e-45a7-86f2-8c9a6d0c73e0",
                            RoleId = "34f669a9-3c3b-4c0d-a320-c1143f295621"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScheduleCentral.Models.AcademicPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AcademicPeriods");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvailabilitySlots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableHours")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSelfRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b1f8e5d0-8b1e-45a7-86f2-8c9a6d0c73e0",
                            AccessFailedCount = 0,
                            AvailableHours = 12,
                            ConcurrencyStamp = "b4c6b4bb-452e-4243-845c-2b0e5bfe3c9f",
                            Email = "mikyasabebe76@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mikyas",
                            IsApproved = true,
                            LastName = "Abebe",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIKYASABEBE76@GMAIL.COM",
                            NormalizedUserName = "MIKYASABEBE76@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFJENxhGm2Y85kqWrusZaY0FA/8TWigeh/6PSWZq8Epgs/ExiK3zQLySo6ga7p7TFw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b578d98-ae6a-47ab-9991-3b31bdf1d915",
                            TwoFactorEnabled = true,
                            UserName = "mikyasabebe76@gmail.com"
                        });
                });

            modelBuilder.Entity("ScheduleCentral.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("LabHours")
                        .HasColumnType("int");

                    b.Property<int>("LectureHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CourseOfferings");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseOfferingYearLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsExtension")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionCount")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingYearLevelId");

                    b.HasIndex("CourseOfferingId", "YearLevel", "BatchName")
                        .IsUnique();

                    b.ToTable("CourseOfferingBatches");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedContactHours")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("bit");

                    b.Property<int?>("OfferingBatchId")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("OfferingBatchId");

                    b.HasIndex("RoomId");

                    b.ToTable("CourseOfferingSections");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingSectionInstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseOfferingSectionId")
                        .HasColumnType("int");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("CourseOfferingSectionId", "InstructorId")
                        .IsUnique();

                    b.ToTable("CourseOfferingSectionInstructors");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingYearLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.ToTable("CourseOfferingYearLevels");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ScheduleCentral.Models.InstructorCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId", "CourseId")
                        .IsUnique();

                    b.ToTable("InstructorQualifications");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ScheduleCentral.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Additional seating",
                            Name = "Lecture Hall"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Workstations provided",
                            Name = "Computer Lab"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drafting tables and open space",
                            Name = "Design Studio"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Standard tier seating",
                            Name = "Lecture Room"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Standard tier seating room with projector",
                            Name = "Projector Room"
                        });
                });

            modelBuilder.Entity("ScheduleCentral.Models.ScheduleGrid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId")
                        .IsUnique();

                    b.ToTable("ScheduleGrids");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ScheduleMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleGridId")
                        .HasColumnType("int");

                    b.Property<int?>("SchedulePublicationId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotLength")
                        .HasColumnType("int");

                    b.Property<int>("SlotStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ScheduleGridId");

                    b.HasIndex("SchedulePublicationId");

                    b.ToTable("ScheduleMeetings");
                });

            modelBuilder.Entity("ScheduleCentral.Models.SchedulePublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SchedulePublications");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ScheduleSwapRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedPublicationId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinalReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalReviewerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InitialReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitialReviewerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("PeerDecision")
                        .HasColumnType("int");

                    b.Property<string>("PeerInstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PeerRespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeerScheduleMeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequesterInstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleMeetingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetDayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("TargetSlotStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeerInstructorId");

                    b.HasIndex("PeerScheduleMeetingId");

                    b.HasIndex("RequesterInstructorId");

                    b.HasIndex("ScheduleMeetingId");

                    b.ToTable("ScheduleSwapRequests");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsExtension")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("ScheduleCentral.Models.SectionRoomRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseOfferingSectionId")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingSectionId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("SectionRoomRequirements");
                });

            modelBuilder.Entity("ScheduleCentral.Models.SemesterCourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SectionId");

                    b.ToTable("SemesterAssignments");
                });

            modelBuilder.Entity("ScheduleCentral.Models.YearBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("YearLevelId");

                    b.ToTable("YearBatches");
                });

            modelBuilder.Entity("ScheduleCentral.Models.YearLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("YearLevels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ScheduleCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ScheduleCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ScheduleCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleCentral.Models.Batch", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Department", "Department")
                        .WithMany("Batches")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Course", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Department", null)
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingBatch", b =>
                {
                    b.HasOne("ScheduleCentral.Models.CourseOffering", "CourseOffering")
                        .WithMany("Batches")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.CourseOfferingYearLevel", null)
                        .WithMany("Batches")
                        .HasForeignKey("CourseOfferingYearLevelId");

                    b.Navigation("CourseOffering");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingSection", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.CourseOffering", "CourseOffering")
                        .WithMany("Sections")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "Instructor")
                        .WithMany("AssignedSections")
                        .HasForeignKey("InstructorId");

                    b.HasOne("ScheduleCentral.Models.CourseOfferingBatch", "OfferingBatch")
                        .WithMany("Sections")
                        .HasForeignKey("OfferingBatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScheduleCentral.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Course");

                    b.Navigation("CourseOffering");

                    b.Navigation("Instructor");

                    b.Navigation("OfferingBatch");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingSectionInstructor", b =>
                {
                    b.HasOne("ScheduleCentral.Models.CourseOfferingSection", "CourseOfferingSection")
                        .WithMany("SectionInstructors")
                        .HasForeignKey("CourseOfferingSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOfferingSection");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingYearLevel", b =>
                {
                    b.HasOne("ScheduleCentral.Models.CourseOffering", "CourseOffering")
                        .WithMany("YearLevels")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Department", b =>
                {
                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId");

                    b.Navigation("Head");
                });

            modelBuilder.Entity("ScheduleCentral.Models.InstructorCourse", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "Instructor")
                        .WithMany("QualifiedCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Room", b =>
                {
                    b.HasOne("ScheduleCentral.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ScheduleGrid", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ScheduleMeeting", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("ScheduleCentral.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("ScheduleCentral.Models.ScheduleGrid", "ScheduleGrid")
                        .WithMany()
                        .HasForeignKey("ScheduleGridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.SchedulePublication", "SchedulePublication")
                        .WithMany("Meetings")
                        .HasForeignKey("SchedulePublicationId");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Room");

                    b.Navigation("ScheduleGrid");

                    b.Navigation("SchedulePublication");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ScheduleSwapRequest", b =>
                {
                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "PeerInstructor")
                        .WithMany()
                        .HasForeignKey("PeerInstructorId");

                    b.HasOne("ScheduleCentral.Models.ScheduleMeeting", "PeerScheduleMeeting")
                        .WithMany()
                        .HasForeignKey("PeerScheduleMeetingId");

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "RequesterInstructor")
                        .WithMany()
                        .HasForeignKey("RequesterInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.ScheduleMeeting", "ScheduleMeeting")
                        .WithMany()
                        .HasForeignKey("ScheduleMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerInstructor");

                    b.Navigation("PeerScheduleMeeting");

                    b.Navigation("RequesterInstructor");

                    b.Navigation("ScheduleMeeting");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Section", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Batch", "Batch")
                        .WithMany("Sections")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ScheduleCentral.Models.SectionRoomRequirement", b =>
                {
                    b.HasOne("ScheduleCentral.Models.CourseOfferingSection", "CourseOfferingSection")
                        .WithMany("RoomRequirements")
                        .HasForeignKey("CourseOfferingSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOfferingSection");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("ScheduleCentral.Models.SemesterCourseAssignment", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCentral.Models.ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("ScheduleCentral.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("ScheduleCentral.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Room");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ScheduleCentral.Models.YearBatch", b =>
                {
                    b.HasOne("ScheduleCentral.Models.CourseOffering", "CourseOffering")
                        .WithMany()
                        .HasForeignKey("CourseOfferingId");

                    b.HasOne("ScheduleCentral.Models.YearLevel", "YearLevel")
                        .WithMany("Batches")
                        .HasForeignKey("YearLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("YearLevel");
                });

            modelBuilder.Entity("ScheduleCentral.Models.YearLevel", b =>
                {
                    b.HasOne("ScheduleCentral.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleCentral.Models.ApplicationUser", b =>
                {
                    b.Navigation("AssignedSections");

                    b.Navigation("QualifiedCourses");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Batch", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOffering", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Sections");

                    b.Navigation("YearLevels");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingBatch", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingSection", b =>
                {
                    b.Navigation("RoomRequirements");

                    b.Navigation("SectionInstructors");
                });

            modelBuilder.Entity("ScheduleCentral.Models.CourseOfferingYearLevel", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("ScheduleCentral.Models.Department", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("ScheduleCentral.Models.SchedulePublication", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("ScheduleCentral.Models.YearLevel", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
