import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import DashboardLayout from './components/DashboardLayout';
// Placeholder components to prevent errors
const WelcomeDashboard = ({ session }) => (_jsxs("div", { className: 'p-6 bg-white rounded-xl shadow-lg', children: [_jsxs("h1", { className: 'text-3xl font-bold text-gray-900', children: ["Welcome back, ", session.userName, "!"] }), _jsxs("p", { className: 'mt-2 text-lg text-indigo-600', children: ["Your role: ", session.roles.join(', ') || 'User'] }), _jsx("p", { className: 'mt-4 text-gray-600', children: "Use the sidebar to navigate your specific tasks." })] }));
const PlaceholderPage = ({ title }) => (_jsxs("div", { className: 'p-6 bg-white rounded-xl shadow-lg', children: [_jsx("h1", { className: 'text-3xl font-bold text-gray-900', children: title }), _jsxs("p", { className: 'mt-2 text-gray-500', children: ["Content for ", title, " will be built here."] })] }));
const App = ({ session }) => {
    if (!session.isAuthenticated) {
        return (_jsx("div", { className: "flex min-h-[80vh] flex-1 flex-col justify-center px-6 py-12 lg:px-8", children: _jsxs("div", { className: "sm:mx-auto sm:w-full sm:max-w-sm", children: [_jsx("h2", { className: "mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900", children: "Authentication Required" }), _jsx("div", { className: "mt-6 text-center", children: _jsx("a", { href: "/Identity/Account/Login", className: "inline-flex justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500", rel: "external", children: "Go to Login Page \u2192" }) })] }) }));
    }
    return (_jsx(DashboardLayout, { session: session, children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(WelcomeDashboard, { session: session }) }), _jsx(Route, { path: "/tm/reports", element: _jsx(PlaceholderPage, { title: "Reports & Analytics" }) }), _jsx(Route, { path: "/dept/management", element: _jsx(PlaceholderPage, { title: "Department Management" }) }), _jsx(Route, { path: "/po/courses", element: _jsx(PlaceholderPage, { title: "Manage Courses" }) }), _jsx(Route, { path: "/po/rooms", element: _jsx(PlaceholderPage, { title: "Manage Rooms" }) }), _jsx(Route, { path: "/po/generate", element: _jsx(PlaceholderPage, { title: "Generate Schedule" }) }), _jsx(Route, { path: "/instructor/schedule", element: _jsx(PlaceholderPage, { title: "My Teaching Schedule" }) }), _jsx(Route, { path: "/instructor/requests", element: _jsx(PlaceholderPage, { title: "Swap Request Management" }) }), _jsx(Route, { path: "/admin/users", element: _jsx(PlaceholderPage, { title: "User Management" }) }), _jsx(Route, { path: "/admin/settings", element: _jsx(PlaceholderPage, { title: "System Settings" }) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }));
};
export default App;
